import 'package:library_architecture_mvvm_modify/library_architecture_mvvm_modify.dart';
import 'package:meta/meta.dart';
import 'package:web_topdbd/data_for_named/data_for_ip_address_firestore_system_view/data_for_ip_address_firestore_system_view.dart';

@immutable
final class InitializedDefaultStreamStateQDataForIPAddressFirestoreSystemView extends BaseInitializedNamedStreamStateQDataForNamed<DataForIPAddressFirestoreSystemView> {
  @override
  BaseNamedStreamStateQDataForNamed<DataForIPAddressFirestoreSystemView> get getNamedStreamStateQDataForNamed =>
      DefaultStreamStateQDataForNamed<DataForIPAddressFirestoreSystemView>(DataForIPAddressFirestoreSystemView(true,false));
}