import 'package:library_architecture_mvvm_modify/library_architecture_mvvm_modify.dart';
import 'package:meta/meta.dart';
import 'package:web_topdbd/data_for_named/data_for_initialize_service_system_view/data_for_initialize_service_system_view.dart';

@immutable
final class InitializedDefaultStreamStateQDataForInitializeServiceSystemView extends BaseInitializedNamedStreamStateQDataForNamed<DataForInitializeServiceSystemView> {
  @override
  BaseNamedStreamStateQDataForNamed<DataForInitializeServiceSystemView> get getNamedStreamStateQDataForNamed =>
      DefaultStreamStateQDataForNamed<DataForInitializeServiceSystemView>(DataForInitializeServiceSystemView(true));
}