import 'package:meta/meta.dart';

@immutable
final class KeysExceptionUtility {
  /* UNKNOWN */
  static const String uNKNOWN = "uNKNOWN";
  /* DataForAntiDDosSystemView */
  static const String dataForAntiDDosSystemViewQGetStringWhereNotEqualsParametersCodeAndInputCode = "dataForAntiDDosSystemViewQGetStringWhereNotEqualsParametersCodeAndInputCode";
  /* GetEEDiscordUserFirestoreEEFromUniqueIdEEParameterFirebaseFirestoreService */
  static const String getEEDiscordUserFirestoreEEFromUniqueIdEEParameterFirebaseFirestoreService = "getEEDiscordUserFirestoreEEFromUniqueIdEEParameterFirebaseFirestoreService";
  /* GetEEDiscordUserFirestoreEEFromUniqueIdByUserEEParameterFirebaseFirestoreService */
  static const String getEEDiscordUserFirestoreEEFromUniqueIdByUserEEParameterFirebaseFirestoreService = "getEEDiscordUserFirestoreEEFromUniqueIdByUserEEParameterFirebaseFirestoreService";
  /* GetQQIPAddressFirestoreQFirebaseFirestoreServiceQParameterStringQQForUniqueIdByUser */
  static const String getQQIPAddressFirestoreQFirebaseFirestoreServiceQParameterStringQQForUniqueIdByUser = "getQQIPAddressFirestoreQFirebaseFirestoreServiceQParameterStringQQForUniqueIdByUser";
  /* UserQFirebaseFirestoreServiceViewModelUsingInsertParameterStringForUniqueId */
  static const String userQFirebaseFirestoreServiceViewModelUsingInsertParameterStringForUniqueIdQWhereLocalExceptionGuiltyUserNoExists = "userQFirebaseFirestoreServiceViewModelUsingInsertParameterStringForUniqueIdQWhereLocalExceptionGuiltyUserNoExists";
  /* UserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueId */
  static const String userQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdQWhereLocalExceptionGuiltyUserNoExists = "userQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdQWhereLocalExceptionGuiltyUserNoExists";
  /* InsertEEDiscordUserFirestoreEEFromRegistrationDiscordUserFirestoreUtilityEEParameterFirebaseFirestoreService */
  static const String insertEEDiscordUserFirestoreEEFromRegistrationDiscordUserFirestoreUtilityEEParameterFirebaseFirestoreService = "insertEEDiscordUserFirestoreEEFromRegistrationDiscordUserFirestoreUtilityEEParameterFirebaseFirestoreService";
  /* UpdateQQDiscordUserFirestoreQFirebaseFirestoreServiceQParameterUpdateUsernameAndGlobalNameToDiscordUserFirestoreUtility */
  static const String updateQQDiscordUserFirestoreQFirebaseFirestoreServiceQParameterUpdateUsernameAndGlobalNameToDiscordUserFirestoreUtility = "updateQQDiscordUserFirestoreQFirebaseFirestoreServiceQParameterUpdateUsernameAndGlobalNameToDiscordUserFirestoreUtility";
  /* UpdateQQIPAddressFirestoreQFirebaseFirestoreServiceQParameterIPToIPAddressFirestoreUtility */
  static const String updateQQIPAddressFirestoreQFirebaseFirestoreServiceQParameterIPToIPAddressFirestoreUtility = "updateQQIPAddressFirestoreQFirebaseFirestoreServiceQParameterIPToIPAddressFirestoreUtility";
  /* UpdateQQLastLoginTimeUserQFirebaseFirestoreServiceQParameterStringQQForUniqueIdByUser */
  static const String updateQQLastLoginTimeUserQFirebaseFirestoreServiceQParameterStringQQForUniqueIdByUser = "updateQQLastLoginTimeUserQFirebaseFirestoreServiceQParameterStringQQForUniqueIdByUser";
  /* VerifiedUserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdByUser */
  static const String verifiedUserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdByUserQWhereLocalExceptionGuiltyUserNoExists = "verifiedUserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdByUserQWhereLocalExceptionGuiltyUserNoExists";
  /* VerifiedUserQFirebaseFirestoreServiceViewModelUsingCustomStartListeningAndCancelListening */
  static const String verifiedUserQFirebaseFirestoreServiceViewModelUsingCustomStartListeningAndCancelListeningQWhereLocalExceptionGuiltyUserNoExists = "verifiedUserQFirebaseFirestoreServiceViewModelUsingCustomStartListeningAndCancelListeningQWhereLocalExceptionGuiltyUserNoExists";
  /* StartListeningAndCancelListeningQQIPAddressFirestoreQFirebaseFirestoreServiceQParameterStringAndFunctionQQForUniqueIdByUserAndCallbackToReturn */
  static const String startListeningAndCancelListeningQQIPAddressFirestoreQFirebaseFirestoreServiceQParameterStringAndFunctionQQForUniqueIdByUserAndCallbackToReturn = "startListeningAndCancelListeningQQIPAddressFirestoreQFirebaseFirestoreServiceQParameterStringAndFunctionQQForUniqueIdByUserAndCallbackToReturn";
  /* GetEECountryEEFromUniqueIdByUserEEParameterFirebaseFirestoreService */
  static const String getEECountryEEFromUniqueIdByUserEEParameterFirebaseFirestoreService = "getEECountryEEFromUniqueIdByUserEEParameterFirebaseFirestoreService";
  /* GetEEAboutMeEEFromUniqueIdByUserEEParameterFirebaseFirestoreService */
  static const String getEEAboutMeEEFromUniqueIdByUserEEParameterFirebaseFirestoreService = "getEEAboutMeEEFromUniqueIdByUserEEParameterFirebaseFirestoreService";
  /* RoleUserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdByUser */
  static const String roleUserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdByUserQWhereLocalExceptionGuiltyUserNoExists = "roleUserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdByUserQWhereLocalExceptionGuiltyUserNoExists";
  /* StatsQFirebaseFirestoreServiceViewModelUsingGetParameterGetUniqueIdByUserAndSeasonNumberBySeasonToStatsUtility */
  static const String statsQFirebaseFirestoreServiceViewModelUsingGetParameterGetUniqueIdByUserAndSeasonNumberBySeasonToStatsUtilityQWhereLocalExceptionGuiltyUserNoExists = "statsQFirebaseFirestoreServiceViewModelUsingGetParameterGetUniqueIdByUserAndSeasonNumberBySeasonToStatsUtilityQWhereLocalExceptionGuiltyUserNoExists";
  /* VerifiedUserQFirebaseFirestoreServiceViewModelUsingInsertParameterRegistrationVerifiedUserUtility */
  static const String verifiedUserQFirebaseFirestoreServiceViewModelUsingInsertParameterRegistrationVerifiedUserUtilityQWhereLocalExceptionGuiltyUserNoExists = "verifiedUserQFirebaseFirestoreServiceViewModelUsingInsertParameterRegistrationVerifiedUserUtilityQWhereLocalExceptionGuiltyUserNoExists";
  /* GetQQLastLoginTimeUserQFirebaseFirestoreServiceQParameterStringQQForUniqueIdByUser */
  static const String getQQLastLoginTimeUserQFirebaseFirestoreServiceQParameterStringQQForUniqueIdByUser = "getQQLastLoginTimeUserQFirebaseFirestoreServiceQParameterStringQQForUniqueIdByUser";
  /* InsertQQLastLoginTimeUserQFirebaseFirestoreServiceQParameterStringQQForUniqueIdByUser */
  static const String insertQQLastLoginTimeUserQFirebaseFirestoreServiceQParameterStringQQForUniqueIdByUser = "insertQQLastLoginTimeUserQFirebaseFirestoreServiceQParameterStringQQForUniqueIdByUser";
  /* RoleUserQFirebaseFirestoreServiceViewModelUsingInsertParameterStringForUniqueIdByUser */
  static const String roleUserQFirebaseFirestoreServiceViewModelUsingInsertParameterStringForUniqueIdByUserQWhereLocalExceptionGuiltyUserNoExists = "roleUserQFirebaseFirestoreServiceViewModelUsingInsertParameterStringForUniqueIdByUserQWhereLocalExceptionGuiltyUserNoExists";
  /* InsertQQIPAddressFirestoreQFirebaseFirestoreServiceQParameterRegistrationIPAddressFirestoreUtility */
  static const String insertQQIPAddressFirestoreQFirebaseFirestoreServiceQParameterRegistrationIPAddressFirestoreUtility = "insertQQIPAddressFirestoreQFirebaseFirestoreServiceQParameterRegistrationIPAddressFirestoreUtility";
  /* InsertEECountryEEFromRegistrationCountryUtilityEEParameterFirebaseFirestoreService */
  static const String insertEECountryEEFromRegistrationCountryUtilityEEParameterFirebaseFirestoreService = "insertEECountryEEFromRegistrationCountryUtilityEEParameterFirebaseFirestoreService";
  /* DiscordUser */
  static const String discordUserQGetStringWhereNotEqualsFromUsernameAndGlobalNameParametersUsernameAndGlobalName = "discordUserQGetStringWhereNotEqualsFromUsernameAndGlobalNameParametersUsernameAndGlobalName";
  static const String discordUserQGetStringWhereNotEqualsFromUsernameAndGlobalNameParametersUsernameAndGlobalNameTWO = "discordUserQGetStringWhereNotEqualsFromUsernameAndGlobalNameParametersUsernameAndGlobalNameTWO";
  /* InsertEEAboutMeEEFromUniqueIdByUserEEParameterFirebaseFirestoreService */
  static const String insertEEAboutMeEEFromUniqueIdByUserEEParameterFirebaseFirestoreService = "insertEEAboutMeEEFromUniqueIdByUserEEParameterFirebaseFirestoreService";
  /* StatsQFirebaseFirestoreServiceViewModelUsingInsertParameterRegistrationStatsUtility */
  static const String statsQFirebaseFirestoreServiceViewModelUsingInsertParameterRegistrationStatsUtilityQWhereLocalExceptionGuiltyUserNoExists = "statsQFirebaseFirestoreServiceViewModelUsingInsertParameterRegistrationStatsUtilityQWhereLocalExceptionGuiltyUserNoExists";
  /* SeasonQFirebaseFirestoreServiceViewModelUsingGetNPForLastSeasonWhereSortParameterSeasonNumber */
  static const String seasonQFirebaseFirestoreServiceViewModelUsingGetNPForLastSeasonWhereSortParameterSeasonNumberQWhereLocalExceptionGuiltyUserNoExists = "seasonQFirebaseFirestoreServiceViewModelUsingGetNPForLastSeasonWhereSortParameterSeasonNumberQWhereLocalExceptionGuiltyUserNoExists";
  /* IPAddress */
  static const String iPAddressQGetStringWhereNotEqualsFromNameCountryParameterNameCountry = "iPAddressQGetStringWhereNotEqualsFromNameCountryParameterNameCountry";
  static const String iPAddressQGetStringWhereNotEqualsFromIpParameterIp = "iPAddressQGetStringWhereNotEqualsFromIpParameterIp";
  /* IPAddressFirestore */
  static const String iPAddressFirestoreQGetStringWhereNotEqualsFromIpParameterIp = "iPAddressFirestoreQGetStringWhereNotEqualsFromIpParameterIp";
  /* User */
  static const String userQGetStringWhereIsEmptyParameterUniqueId = "userQGetStringWhereIsEmptyParameterUniqueId";
  /* TOPDBDVersionWeb */
  static const String tOPDBDVersionWebQGetStringWhereNotEqualsFromVersionParameterVersion = "tOPDBDVersionWebQGetStringWhereNotEqualsFromVersionParameterVersion";
  /* VerifiedUser */
  static const String verifiedUserQGetStringWhereIsNotVerifiedUserParameterIsVerifiedUser = "verifiedUserQGetStringWhereIsNotVerifiedUserParameterIsVerifiedUser";

  const KeysExceptionUtility._();
}