final class KeysExceptionUtility {
  /* UNKNOWN */
  static const String uNKNOWN = "uNKNOWN";
  /* DataForAntiDDosSystemView */
  static const String dataForAntiDDosSystemViewQGetStringWhereNotEqualsParametersCodeAndInputCode = "dataForAntiDDosSystemViewQGetStringWhereNotEqualsParametersCodeAndInputCode";
  /* DiscordUserFirestoreQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueId */
  static const String discordUserFirestoreQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdQWhereLocalExceptionGuiltyUserNoExists = "discordUserFirestoreQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdQWhereLocalExceptionGuiltyUserNoExists";
  /* UserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdWhereRegistration */
  static const String userQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdWhereRegistrationQWhereLocalExceptionGuiltyUserNoExists = "userQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdWhereRegistrationQWhereLocalExceptionGuiltyUserNoExists";
  /* DiscordUserFirestoreQFirebaseFirestoreServiceViewModelUsingGetParameterRegistrationDiscordUserFirestoreUtility */
  static const String discordUserFirestoreQFirebaseFirestoreServiceViewModelUsingGetParameterRegistrationDiscordUserFirestoreUtilityQWhereLocalExceptionGuiltyUserNoExists = "discordUserFirestoreQFirebaseFirestoreServiceViewModelUsingGetParameterRegistrationDiscordUserFirestoreUtilityQWhereLocalExceptionGuiltyUserNoExists";
  /* VerifiedUserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdByUser */
  static const String verifiedUserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdByUserQWhereLocalExceptionGuiltyUserNoExists = "verifiedUserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdByUserQWhereLocalExceptionGuiltyUserNoExists";
  /* VerifiedUserQFirebaseFirestoreServiceViewModelUsingGetParameterRegistrationVerifiedUserUtility */
  static const String verifiedUserQFirebaseFirestoreServiceViewModelUsingGetParameterRegistrationVerifiedUserUtilityQWhereLocalExceptionGuiltyUserNoExists = "verifiedUserQFirebaseFirestoreServiceViewModelUsingGetParameterRegistrationVerifiedUserUtilityQWhereLocalExceptionGuiltyUserNoExists";
  /* LastLoginTimeUserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdByUserWhereRegistration */
  static const String lastLoginTimeUserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdByUserWhereRegistrationQWhereLocalExceptionGuiltyUserNoExists = "lastLoginTimeUserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdByUserWhereRegistrationQWhereLocalExceptionGuiltyUserNoExists";
  /* LastLoginTimeUserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdByUser */
  static const String lastLoginTimeUserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdByUserQWhereLocalExceptionGuiltyUserNoExists = "lastLoginTimeUserQFirebaseFirestoreServiceViewModelUsingGetParameterStringForUniqueIdByUserQWhereLocalExceptionGuiltyUserNoExists";
  /* IPAddressFirestoreQFirebaseFirestoreServiceViewModelUsingGetParameterRegistrationIPAddressFirestoreUtility */
  static const String iPAddressFirestoreQFirebaseFirestoreServiceViewModelUsingGetParameterRegistrationIPAddressFirestoreUtilityQWhereLocalExceptionGuiltyUserNoExists = "iPAddressFirestoreQFirebaseFirestoreServiceViewModelUsingGetParameterRegistrationIPAddressFirestoreUtilityQWhereLocalExceptionGuiltyUserNoExists";
  /* CountryQFirebaseFirestoreServiceViewModelUsingGetParameterRegistrationCountryUtility */
  static const String countryQFirebaseFirestoreServiceViewModelUsingGetParameterRegistrationCountryUtilityQWhereLocalExceptionGuiltyUserNoExists = "countryQFirebaseFirestoreServiceViewModelUsingGetParameterRegistrationCountryUtilityQWhereLocalExceptionGuiltyUserNoExists";
  /* DiscordUser */
  static const String discordUserQGetStringFromUsernameAndGlobalNameWhereNotEqualsParametersUsernameAndGlobalName = "discordUserQGetStringFromUsernameAndGlobalNameWhereNotEqualsParametersUsernameAndGlobalName";
  static const String discordUserQGetStringFromUsernameAndGlobalNameWhereNotEqualsParametersUsernameAndGlobalNameTWO = "discordUserQGetStringFromUsernameAndGlobalNameWhereNotEqualsParametersUsernameAndGlobalNameTWO";

  KeysExceptionUtility._();
}