name: windows_topdbd
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: 3.16.2

dependencies:
  common_topdbd:
    path: ../common_topdbd
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  library_architecture_mvvm_modify: ^0.3.1
  intl: ^0.18.0
  meta: ^1.10.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/app_icon.ico
    - assets/icon/app_icon.png