name: windows_topdbd
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: 3.13.0

dependencies:
  common_topdbd:
    path: ../common_topdbd
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  library_architecture_mvvm_modify: ^0.2.5
  intl: ^0.18.0
  meta: ^1.9.1

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/app_icon.ico
    - assets/icon/app_icon.png