name: web_topdbd
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: 3.13.0

dependencies:
  common_topdbd:
    path: ../common_topdbd
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  library_architecture_mvvm_modify: ^0.1.5
  intl: ^0.18.0
  responsive_framework: ^1.1.0
  meta: ^1.9.1
  firebase_core: ^2.10.0
  flutter_web_auth_2_platform_interface: ^2.1.4
  flutter_web_auth_2: ^2.1.4
  http: ^0.13.5
  shared_preferences: ^2.1.0
  cloud_firestore: ^4.5.3
  firebase_auth: ^4.6.1
  top_snackbar_flutter: ^3.1.0
  custom_signin_buttons: ^1.0.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/app_icon.ico
    - assets/icon/app_icon.png
    - assets/txt/terms_of_use_topdbd.txt