name: web_topdbd
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: 3.13.0

dependencies:
  common_topdbd:
    path: ../common_topdbd
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  library_architecture_mvvm_modify: ^0.1.7
  intl: ^0.18.0
  responsive_framework: ^1.1.0
  meta: ^1.9.1
  firebase_core: ^2.15.1
  flutter_web_auth_2_platform_interface: ^2.1.4
  flutter_web_auth_2: ^2.2.1
  http: ^1.1.0
  shared_preferences: ^2.1.0
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  top_snackbar_flutter: ^3.1.0
  custom_signin_buttons: ^1.0.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/app_icon.ico
    - assets/icon/app_icon.png
    - assets/icon/dbd/maniac/maniac_anna.png
    - assets/icon/dbd/maniac/maniac_bilyas.png
    - assets/icon/dbd/maniac/maniac_bubba.png
    - assets/icon/dbd/maniac/maniac_demogorgon.png
    - assets/icon/dbd/maniac/maniac_doctor.png
    - assets/icon/dbd/maniac/maniac_kolya.png
    - assets/icon/dbd/maniac/maniac_mor.png
    - assets/icon/dbd/maniac/maniac_nurse.png
    - assets/icon/dbd/maniac/maniac_trapper.png
    - assets/icon/dbd/maniac/maniac_vesker.png
    - assets/icon/dbd/maps/maps_asy_chapel.png
    - assets/icon/dbd/maps/maps_ind_coal_tower.png
    - assets/icon/dbd/maps/maps_ind_mine.png
    - assets/icon/dbd/maps/maps_ind_storehouse.png
    - assets/icon/dbd/maps/maps_jnk_gas_station.png
    - assets/icon/dbd/maps/maps_jnk_scrapyard.png
    - assets/icon/flags/france.png
    - assets/txt/terms_of_use_topdbd.txt