name: web_topdbd
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: 3.13.0

dependencies:
  common_topdbd:
    path: ../common_topdbd
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  library_architecture_mvvm_modify: ^0.2.4
  intl: ^0.18.0
  responsive_framework: ^1.1.0
  meta: ^1.9.1
  firebase_core: ^2.15.1
  flutter_web_auth_2_platform_interface: ^2.1.4
  flutter_web_auth_2: ^2.2.1
  http: ^1.1.0
  shared_preferences: ^2.1.0
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  top_snackbar_flutter: ^3.1.0
  custom_signin_buttons: ^1.0.2
  uuid: ^3.0.7
  footer: ^0.0.4
  go_router: ^11.1.3

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/app_icon.ico
    - assets/icon/app_icon.png
    - assets/icon/dbd/maniac/maniac_anna.png
    - assets/icon/dbd/maniac/maniac_bilyas.png
    - assets/icon/dbd/maniac/maniac_bubba.png
    - assets/icon/dbd/maniac/maniac_demogorgon.png
    - assets/icon/dbd/maniac/maniac_doctor.png
    - assets/icon/dbd/maniac/maniac_kolya.png
    - assets/icon/dbd/maniac/maniac_mor.png
    - assets/icon/dbd/maniac/maniac_nurse.png
    - assets/icon/dbd/maniac/maniac_trapper.png
    - assets/icon/dbd/maniac/maniac_vesker.png
    - assets/icon/dbd/maps/maps_asy_chapel.png
    - assets/icon/dbd/maps/maps_ind_coal_tower.png
    - assets/icon/dbd/maps/maps_ind_mine.png
    - assets/icon/dbd/maps/maps_ind_storehouse.png
    - assets/icon/dbd/maps/maps_jnk_gas_station.png
    - assets/icon/dbd/maps/maps_jnk_scrapyard.png
    - assets/icon/flags/abkhazia.png
    - assets/icon/flags/afghanistan.png
    - assets/icon/flags/aland.png
    - assets/icon/flags/albania.png
    - assets/icon/flags/algeria.png
    - assets/icon/flags/american_samoa.png
    - assets/icon/flags/andorra.png
    - assets/icon/flags/angola.png
    - assets/icon/flags/anguilla.png
    - assets/icon/flags/antarctica.png
    - assets/icon/flags/antigua_and_barbuda.png
    - assets/icon/flags/argentina.png
    - assets/icon/flags/aruba.png
    - assets/icon/flags/australia.png
    - assets/icon/flags/austria.png
    - assets/icon/flags/azerbaijan.png
    - assets/icon/flags/bahamas.png
    - assets/icon/flags/bahrain.png
    - assets/icon/flags/bangladesh.png
    - assets/icon/flags/barbados.png
    - assets/icon/flags/basque_country.png
    - assets/icon/flags/belarus.png
    - assets/icon/flags/belgium.png
    - assets/icon/flags/belize.png
    - assets/icon/flags/benin.png
    - assets/icon/flags/bermuda.png
    - assets/icon/flags/bhutan.png
    - assets/icon/flags/bolivia.png
    - assets/icon/flags/bosnia_and_herzegovina.png
    - assets/icon/flags/botswana.png
    - assets/icon/flags/brazil.png
    - assets/icon/flags/british_antarctic_territory.png
    - assets/icon/flags/british_virgin_islands.png
    - assets/icon/flags/brunei.png
    - assets/icon/flags/bulgaria.png
    - assets/icon/flags/burkina_faso.png
    - assets/icon/flags/burundi.png
    - assets/icon/flags/cambodia.png
    - assets/icon/flags/cameroon.png
    - assets/icon/flags/canada.png
    - assets/icon/flags/canary_islands.png
    - assets/icon/flags/cape_verde.png
    - assets/icon/flags/cayman_islands.png
    - assets/icon/flags/central_african_republic.png
    - assets/icon/flags/chad.png
    - assets/icon/flags/chile.png
    - assets/icon/flags/china.png
    - assets/icon/flags/christmas_island.png
    - assets/icon/flags/cocos_keeling_islands.png
    - assets/icon/flags/colombia.png
    - assets/icon/flags/commonwealth.png
    - assets/icon/flags/comoros.png
    - assets/icon/flags/cook_islands.png
    - assets/icon/flags/costa_rica.png
    - assets/icon/flags/cote_divoire.png
    - assets/icon/flags/croatia.png
    - assets/icon/flags/cuba.png
    - assets/icon/flags/curacao.png
    - assets/icon/flags/cyprus.png
    - assets/icon/flags/czech_republic.png
    - assets/icon/flags/democratic_republic_of_the_congo.png
    - assets/icon/flags/denmark.png
    - assets/icon/flags/djibouti.png
    - assets/icon/flags/dominica.png
    - assets/icon/flags/dominican_republic.png
    - assets/icon/flags/east_timor.png
    - assets/icon/flags/ecuador.png
    - assets/icon/flags/egypt.png
    - assets/icon/flags/el_salvador.png
    - assets/icon/flags/england.png
    - assets/icon/flags/equatorial_guinea.png
    - assets/icon/flags/eritrea.png
    - assets/icon/flags/estonia.png
    - assets/icon/flags/ethiopia.png
    - assets/icon/flags/european_union.png
    - assets/icon/flags/falkland_islands.png
    - assets/icon/flags/faroes.png
    - assets/icon/flags/fiji.png
    - assets/icon/flags/finland.png
    - assets/icon/flags/france.png
    - assets/icon/flags/french_polynesia.png
    - assets/icon/flags/french_southern_territories.png
    - assets/icon/flags/gabon.png
    - assets/icon/flags/gambia.png
    - assets/icon/flags/georgia.png
    - assets/icon/flags/germany.png
    - assets/icon/flags/ghana.png
    - assets/icon/flags/gibraltar.png
    - assets/icon/flags/go_squared.png
    - assets/icon/flags/greece.png
    - assets/icon/flags/greenland.png
    - assets/icon/flags/grenada.png
    - assets/icon/flags/guam.png
    - assets/icon/flags/guatemala.png
    - assets/icon/flags/guernsey.png
    - assets/icon/flags/guinea.png
    - assets/icon/flags/guinea_bissau.png
    - assets/icon/flags/guyana.png
    - assets/icon/flags/haiti.png
    - assets/icon/flags/honduras.png
    - assets/icon/flags/hong_kong.png
    - assets/icon/flags/hungary.png
    - assets/icon/flags/iceland.png
    - assets/icon/flags/india.png
    - assets/icon/flags/indonesia.png
    - assets/icon/flags/iran.png
    - assets/icon/flags/iraq.png
    - assets/icon/flags/ireland.png
    - assets/icon/flags/isle_of_man.png
    - assets/icon/flags/israel.png
    - assets/icon/flags/italy.png
    - assets/icon/flags/jamaica.png
    - assets/icon/flags/japan.png
    - assets/icon/flags/jersey.png
    - assets/icon/flags/jordan.png
    - assets/icon/flags/kazakhstan.png
    - assets/icon/flags/kenya.png
    - assets/icon/flags/kiribati.png
    - assets/icon/flags/kosovo.png
    - assets/icon/flags/kuwait.png
    - assets/icon/flags/kyrgyzstan.png
    - assets/icon/flags/laos.png
    - assets/icon/flags/latvia.png
    - assets/icon/flags/lebanon.png
    - assets/icon/flags/lesotho.png
    - assets/icon/flags/liberia.png
    - assets/icon/flags/libya.png
    - assets/icon/flags/liechtenstein.png
    - assets/icon/flags/lithuania.png
    - assets/icon/flags/luxembourg.png
    - assets/icon/flags/macau.png
    - assets/icon/flags/macedonia.png
    - assets/icon/flags/madagascar.png
    - assets/icon/flags/malawi.png
    - assets/icon/flags/malaysia.png
    - assets/icon/flags/maldives.png
    - assets/icon/flags/mali.png
    - assets/icon/flags/malta.png
    - assets/icon/flags/mars.png
    - assets/icon/flags/marshall_islands.png
    - assets/icon/flags/martinique.png
    - assets/icon/flags/mauritania.png
    - assets/icon/flags/mayotte.png
    - assets/icon/flags/mexico.png
    - assets/icon/flags/micronesia.png
    - assets/icon/flags/moldova.png
    - assets/icon/flags/monaco.png
    - assets/icon/flags/mongolia.png
    - assets/icon/flags/montenegro.png
    - assets/icon/flags/montserrat.png
    - assets/icon/flags/morocco.png
    - assets/icon/flags/mozambique.png
    - assets/icon/flags/myanmar.png
    - assets/icon/flags/nagorno_karabakh.png
    - assets/icon/flags/namibia.png
    - assets/icon/flags/nato.png
    - assets/icon/flags/nauru.png
    - assets/icon/flags/nepal.png
    - assets/icon/flags/netherlands.png
    - assets/icon/flags/netherlands_antilles.png
    - assets/icon/flags/new_caledonia.png
    - assets/icon/flags/new_zealand.png
    - assets/icon/flags/nicaragua.png
    - assets/icon/flags/niger.png
    - assets/icon/flags/nigeria.png
    - assets/icon/flags/niue.png
    - assets/icon/flags/norfolk_island.png
    - assets/icon/flags/north_korea.png
    - assets/icon/flags/northern_cyprus.png
    - assets/icon/flags/northern_mariana_islands.png
    - assets/icon/flags/norway.png
    - assets/icon/flags/olympics.png
    - assets/icon/flags/oman.png
    - assets/icon/flags/pakistan.png
    - assets/icon/flags/palau.png
    - assets/icon/flags/palestine.png
    - assets/icon/flags/panama.png
    - assets/icon/flags/papua_new_guinea.png
    - assets/icon/flags/paraguay.png
    - assets/icon/flags/peru.png
    - assets/icon/flags/philippines.png
    - assets/icon/flags/pitcairn_islands.png
    - assets/icon/flags/poland.png
    - assets/icon/flags/portugal.png
    - assets/icon/flags/puerto_rico.png
    - assets/icon/flags/qatar.png
    - assets/icon/flags/red_cross.png
    - assets/icon/flags/republic_of_the_congo.png
    - assets/icon/flags/romania.png
    - assets/icon/flags/russia.png
    - assets/icon/flags/rwanda.png
    - assets/icon/flags/saint_barthelemy.png
    - assets/icon/flags/saint_helena.png
    - assets/icon/flags/saint_kitts_and_nevis.png
    - assets/icon/flags/saint_lucia.png
    - assets/icon/flags/saint_martin.png
    - assets/icon/flags/saint_vincent_and_the_grenadines.png
    - assets/icon/flags/samoa.png
    - assets/icon/flags/san_marino.png
    - assets/icon/flags/sao_tome_and_principe.png
    - assets/icon/flags/saudi_arabia.png
    - assets/icon/flags/scotland.png
    - assets/icon/flags/senegal.png
    - assets/icon/flags/serbia.png
    - assets/icon/flags/seychelles.png
    - assets/icon/flags/sierra_leone.png
    - assets/icon/flags/singapore.png
    - assets/icon/flags/slovakia.png
    - assets/icon/flags/slovenia.png
    - assets/icon/flags/solomon_islands.png
    - assets/icon/flags/somalia.png
    - assets/icon/flags/somaliland.png
    - assets/icon/flags/south_africa.png
    - assets/icon/flags/south_georgia_and_the_south_sandwich_islands.png
    - assets/icon/flags/south_korea.png
    - assets/icon/flags/south_ossetia.png
    - assets/icon/flags/south_sudan.png
    - assets/icon/flags/spain.png
    - assets/icon/flags/sri_lanka.png
    - assets/icon/flags/sudan.png
    - assets/icon/flags/suriname.png
    - assets/icon/flags/swaziland.png
    - assets/icon/flags/sweden.png
    - assets/icon/flags/switzerland.png
    - assets/icon/flags/syria.png
    - assets/icon/flags/taiwan.png
    - assets/icon/flags/tajikistan.png
    - assets/icon/flags/tanzania.png
    - assets/icon/flags/thailand.png
    - assets/icon/flags/togo.png
    - assets/icon/flags/tokelau.png
    - assets/icon/flags/tonga.png
    - assets/icon/flags/trinidad_and_tobago.png
    - assets/icon/flags/tunisia.png
    - assets/icon/flags/turkey.png
    - assets/icon/flags/turkmenistan.png
    - assets/icon/flags/turks_and_caicos_islands.png
    - assets/icon/flags/tuvalu.png
    - assets/icon/flags/uganda.png
    - assets/icon/flags/ukraine.png
    - assets/icon/flags/united_arab_emirates.png
    - assets/icon/flags/united_kingdom.png
    - assets/icon/flags/united_nations.png
    - assets/icon/flags/united_states.png
    - assets/icon/flags/unknown.png
    - assets/icon/flags/uruguay.png
    - assets/icon/flags/us_virgin_islands.png
    - assets/icon/flags/uzbekistan.png
    - assets/icon/flags/vanuatu.png
    - assets/icon/flags/vatican_city.png
    - assets/icon/flags/venezuela.png
    - assets/icon/flags/vietnam.png
    - assets/icon/flags/wales.png
    - assets/icon/flags/wallis_and_futuna.png
    - assets/icon/flags/western_sahara.png
    - assets/icon/flags/yemen.png
    - assets/icon/flags/zambia.png
    - assets/icon/flags/zimbabwe.png
    - assets/txt/terms_of_use_topdbd.txt