import 'package:library_architecture_mvvm_modify/library_architecture_mvvm_modify.dart';
import 'package:web_topdbd/named_vm/settings_necessary_length_picked_survivor_perk_by_maniac_w_match_balance_vm/enum_data_for_settings_necessary_length_picked_survivor_perk_by_maniac_w_match_balance_view.dart';

final class DataForSettingsNecessaryLengthPickedSurvivorPerkByManiacWMatchBalanceView extends BaseDataForNamed<EnumDataForSettingsNecessaryLengthPickedSurvivorPerkByManiacWMatchBalanceView> {
  String nameByManiacWMatchBalance;
  int necessaryLengthPickedSurvivorPerkByManiacWMatchBalance;

  DataForSettingsNecessaryLengthPickedSurvivorPerkByManiacWMatchBalanceView(super.isLoading,this.nameByManiacWMatchBalance,this.necessaryLengthPickedSurvivorPerkByManiacWMatchBalance);

  @override
  EnumDataForSettingsNecessaryLengthPickedSurvivorPerkByManiacWMatchBalanceView get getEnumDataForNamed {
    if (isLoading) {
      return EnumDataForSettingsNecessaryLengthPickedSurvivorPerkByManiacWMatchBalanceView.isLoading;
    }
    if (exceptionController.isWhereNotEqualsNullParameterException()) {
      return EnumDataForSettingsNecessaryLengthPickedSurvivorPerkByManiacWMatchBalanceView.exception;
    }
    return EnumDataForSettingsNecessaryLengthPickedSurvivorPerkByManiacWMatchBalanceView.success;
  }
}